from snakemake.utils import min_version
import os
import pandas as pd

##### set minimum snakemake version #####
min_version("7.31.1")

### set singularity container for all rules
singularity: "docker://quay.io/preskaa/xengsort:2.0.7"

## params
human_ref = config["human_refgenome"]
mouse_ref = config["mouse_refgenome"]
out_dir = config["out_dir"]
sample_sheet = config["samples"]

### helper functions ####
def extract_metadata(sample_sheet):
    """

    :param sample_sheet: input metadata for samples
    :return: sample id and lanes for WGS
    """
    sample_df = pd.read_csv(sample_sheet, sep="\t")
    sample_id = list(sample_df["sample_id"])[0]
    lanes = list(sample_df["lane"])
    return sample_id, lanes

def _fetch_fastq1(wildcards):
   sample_df = pd.read_csv(config["samples"], sep="\t")
   temp = sample_df[sample_df["lane"] == wildcards.lane]
   fastq = list(temp["fastq_1"])[0]
   return fastq

def _fetch_fastq2(wildcards):
   sample_df = pd.read_csv(config["samples"], sep="\t")
   temp = sample_df[sample_df["lane"] == wildcards.lane]
   fastq = list(temp["fastq_2"])[0]
   return fastq

sample_id, lanes = extract_metadata(sample_sheet)


### target rule ####
rule all:
    input:
        os.path.join(out_dir,"xengsort","xengsort-k25.hash"),
        os.path.join(out_dir,"xengsort","xengsort-k25.info"),
        expand(os.path.join(out_dir, "xengsort/{sample}/{lane}/{sample}-k25-graft.1.fq.gz"),
            sample=sample_id, lane=lanes),
        expand(os.path.join(out_dir,"xengsort/{sample}/{lane}/{sample}_R1.filtered.fastq.gz"),
            sample=sample_id, lane=lanes),
        expand(os.path.join(out_dir,"xengsort/{sample}/{lane}/{sample}_R2.filtered.fastq.gz"),
            sample=sample_id, lane=lanes)

# A rule that demonstrates how to build an index with xengsort
# Note that you need to give an estimate of the number of k-mers in all input files.
# For human and mouse DNA and cDNA, and k=25, this is approx. 4.5 billion,
# so this number is given as size parameter below.
rule build_index:
    input:
        dna_human=human_ref,
        dna_mouse=mouse_ref
    output:
        index_hash = os.path.join(out_dir, "xengsort", "xengsort-k25.hash"),
        index_info = os.path.join(out_dir, "xengsort", "xengsort-k25.info")
    params:
        index = os.path.join(out_dir, "xengsort", "xengsort-k25"),
        size = 4_500_000_000,
        k = 25,
        debug="-DD",  # debug level 2
    threads: 11
    resources:
        mem_mb = 50000,
        time = 360
    shell:
        "xengsort {params.debug} index --index {params.index} \
        -G {input.dna_human} -H {input.dna_mouse} \
        -n {params.size} -W {threads} -k {params.k}"

# A rule that demonstrates 'xengsort classify'
# (In principle, ALL output files should be listed, but all are created together,
#  so if we successfully get the -host.?.fq files, we get all of them.
#  And we do not need to process them any further.)

rule classify_sample:
    input:
        index_hash = os.path.join(out_dir,"xengsort","xengsort-k25.hash"),
        index_info = os.path.join(out_dir,"xengsort","xengsort-k25.info"),
        fastq1 = _fetch_fastq1,
        fastq2 = _fetch_fastq2
    output:
        graft1 = os.path.join(out_dir, "xengsort/{sample}/{lane}/{sample}-k25-graft.1.fq.gz"),
        graft2 = os.path.join(out_dir, "xengsort/{sample}/{lane}/{sample}-k25-graft.2.fq.gz"),
    params:
        index = os.path.join(out_dir, "xengsort", "xengsort-k25"),
        debug="-DD",
        outprefix=os.path.join(out_dir,"xengsort/{sample}/{lane}/{sample}-k25"),
        prefetch=1,
        chunksize=16.0 ## in MB
    threads: 16
    resources:
        mem_mb = 100000,
        time = 1440
    shell:
        "xengsort {params.debug} classify --out {params.outprefix} \
        --index {params.index} --threads {threads} \
        --fastq {input.fastq1} --pairs {input.fastq2} \
        --chunksize {params.chunksize} --mode count --prefetchlevel {params.prefetch}"

### create symlinks to final outputs ...
rule symlink_fastqs:
    input:
        graft1 = os.path.join(out_dir, "xengsort/{sample}/{lane}/{sample}-k25-graft.1.fq.gz"),
        graft2 = os.path.join(out_dir, "xengsort/{sample}/{lane}/{sample}-k25-graft.2.fq.gz"),
    output:
        filtered_fastq1 = os.path.join(out_dir,"xengsort/{sample}/{lane}/{sample}_R1.filtered.fastq.gz"),
        filtered_fastq2= os.path.join(out_dir,"xengsort/{sample}/{lane}/{sample}_R2.filtered.fastq.gz")
    threads: 1
    resources:
        mem_mb = 4000,
        time = 20
    shell:
        """
        ln -s {input.graft1} {output.filtered_fastq1} &&
        ln -s {input.graft2} {output.filtered_fastq2}
        """
