from snakemake.utils import min_version
import os

##### set minimum snakemake version #####
min_version("7.31.1")

### set singularity container for all rules
singularity: "docker://quay.io/preskaa/xengsort:2.0.7"

## params
human_ref = config["human_refgenome"]
mouse_ref = config["mouse_refgenome"]
sample_id = config["sample_id"]
out_dir = config["out_dir"]
fastq1 = config["fastq1"]
fastq2 = config["fastq2"]

rule all:
    input:
        os.path.join(out_dir,"xengsort","xengsort-k25.hash"),
        os.path.join(out_dir,"xengsort","xengsort-k25.info"),
        expand(os.path.join(out_dir, "xengsort/{sample}-k25-graft.1.fq.gz"),
            sample=sample_id),
        expand(os.path.join(out_dir,"xengsort/{sample}.filtered.fastq.gz"),
            sample=sample_id)

# A rule that demonstrates how to build an index with xengsort
# Note that you need to give an estimate of the number of k-mers in all input files.
# For human and mouse DNA and cDNA, and k=25, this is approx. 4.5 billion,
# so this number is given as size parameter below.
rule build_index:
    input:
        dna_human=human_ref,
        dna_mouse=mouse_ref
    output:
        index_hash = os.path.join(out_dir, "xengsort", "xengsort-k25.hash"),
        index_info = os.path.join(out_dir, "xengsort", "xengsort-k25.info")
    params:
        index = os.path.join(out_dir, "xengsort", "xengsort-k25"),
        size = 4_500_000_000,
        k = 25,
        debug="-DD",  # debug level 2
    threads: 11
    resources:
        mem_mb = 50000,
        time = 360
    shell:
        "xengsort {params.debug} index --index {params.index} \
        -G {input.dna_human} -H {input.dna_mouse} \
        -n {params.size} -W {threads} -k {params.k}"

# A rule that demonstrates 'xengsort classify'
# (In principle, ALL output files should be listed, but all are created together,
#  so if we successfully get the -host.?.fq files, we get all of them.
#  And we do not need to process them any further.)

rule classify_sample:
    input:
        index_hash = os.path.join(out_dir,"xengsort","xengsort-k25.hash"),
        index_info = os.path.join(out_dir,"xengsort","xengsort-k25.info"),
        fastq1 = fastq1,
        fastq2 = fastq2
    output:
        graft1 = os.path.join(out_dir, "xengsort/{sample}-k25-graft.1.fq.gz"),
        graft2 = os.path.join(out_dir, "xengsort/{sample}-k25-graft.2.fq.gz"),
    params:
        index = os.path.join(out_dir, "xengsort", "xengsort-k25"),
        debug="-DD",
        outprefix=os.path.join(out_dir,"xengsort", "{sample}-k25"),
        chunksize=16.0
    threads: 8
    resources:
        mem_mb = 100000,
        time = 720
    shell:
        "xengsort {params.debug} classify --out {params.outprefix} \
        --index {params.index} --threads {threads} \
        --fastq {input.fastq1} --pairs {input.fastq2} \
        --chunksize {params.chunksize} --mode count"

### combine graft output into a single fastq ....
rule combine_fastqs:
    input:
        graft1 = os.path.join(out_dir,"xengsort/{sample}-k25-graft.1.fq.gz"),
        graft2 = os.path.join(out_dir,"xengsort/{sample}-k25-graft.2.fq.gz"),
    output:
        filtered_fastq = os.path.join(out_dir,"xengsort/{sample}.filtered.fastq.gz")
    params:
        grafts = os.path.join(out_dir,"xengsort/{sample}-k25-graft.*")
    threads: 1
    resources:
        mem_mb = 50000,
        time = 180
    shell:
        "cat {params.grafts} > {output.filtered_fastq}"