### boiler plate config
out_dir: /data1/shahs3/users/preskaa/APS017.1_Archive/full_test
mouse_refgenome: /data1/shahs3/isabl_data_lake/assemblies/WGS-MM10/mouse/mm10_build38_mouse.fasta
human_refgenome: /data1/shahs3/isabl_data_lake/assemblies/GRCh38-P14/GRCh38.primary_assembly.genome.fa
sample_id: "sampleX"
fastq1: /path/to/sampleX_R1.fastq.gz
fastq2: /path/to/sampleX_R2.fastq.gz